### ISSUE TITLE
Ubuntu 16.04 Support

### ISSUE THREAD

**Issue by cfhammill** [aces/Loris#2287]
Hi,

From the README it seems that currently Ubuntu 16.04 is unsupported. Are there plans for adding
this? And if so what does the timeline look like.

Thanks,

Chris

**Comment by driusan** [comment]
Hi @cfhammil,

Ubuntu 16.04 wasn't released yet when Loris 16.x was under development/being released. It'll be supported with the next release, which should hopefully be out in approximately a month.

If you want to install Loris 16.1 under Ubuntu 16.04, the main problem I would foresee is that MySQL 5.7 is the default version of MySQL that gets installed by apt-get and there are a couple known issues that are only fixed in the development branch. If you're able to install MySQL 5.6 or 5.5, I don't know of any reasons that it shouldn't work.

**Comment by cfhammill** [comment]
Great, thanks for the quick reply. I found some information on getting old MySQL's for Ubuntu 16.04, it looks relatively involved, but certainly do-able.

Thanks again,

Chris
