### ISSUE TITLE
Vagrant: "Installer corrupt" error

### ISSUE THREAD

**Issue by ncote** [aces/Loris#2446]
The Vagrantfile provisioning script downloads https://getcomposer.org/installer  and compares the SHA-384 hash of this file to a fixed value.  The Composer installer gets updated periodically, and the current hash is no longer what we find in the script.  The current hash can be obtained from  https://composer.github.io/installer.sig so it might be better to use this to compare to.

**Comment by driusan** [comment]
Hi @ncote, thanks for the bug report!

I've sent PR #2447 to fix this in the upcoming LORIS 17.0 release (but it won't work until 17.0 is released, since the master branch doesn't yet have the web based database installer that the Vagrantfile depends on.)

If you're trying to use the Vagrant with the 16.1 release, it's probably easiest to just change the hash in the Vagrantfile for now.

**Comment by ncote** [comment]
Hi Dave, great thanks.  That's what I did, and it works fine.

**Comment by driusan** [comment]
Was fixed in #2447 for the next release.
