### ISSUE TITLE
Generated MySQL tables exceed index size with UTF-8

### ISSUE THREAD

**Issue by koyangi-ssi** [aces/Loris#2627]
Hi, 

it seems that the MySQL schema files for behavioural instruments that are generated by the tools/generate_tables_sql_and_testNames.php utility are incompatible with databases using UTF-8 charsets. 

Looking at the relevant parts of  script in question:             
```
$output.="`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',\n";
```

and:

`$output.="PRIMARY KEY  (`CommentID`)\n);\n";`

it is obvious that the field CommentID is used as primary key with a length of 255. Unless strict mode is disabled this exceeds the limit of 767 bytes for the primary key when using InnoDB tables with UTF-8 due to four bytes being used per character. 

As far as I can see there are several possible solutions to this:

* Limit the CommentID field to a length of 191, but I am not sure if CommentIDs can be longer than that
* Explicitly add a charset definition to the generated schema file
* Explicitly state in the requirements for Loris to use a specific charset or to not use strict mode

**Comment by ridz1208** [comment]
Hi @koyangi-ssi,

The issue you bring up is valid and will be fixed in the next iteration. As a temporary solution, you can simply append `ENGINE=InnoDB DEFAULT CHARSET=utf8` to the end or your `CREATE TABLE` statement; 

as per this documentation: https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-utf8.html this uses 3 bytes and will allow the creation of the table.

Further measure will be taken as a permanent fix.

Thank you,
R

**Comment by koyangi-ssi** [comment]
Hi @ridz1208,

thanks for addressing this issue and incorporating a fix in the latest release.
