### ISSUE TITLE
Imaging uploader not displaying error properly

### ISSUE THREAD

**Issue by bopucky** [aces/Loris#4086]
- If the Upload fails for some reason
- The reason for the failure is not shown on the front-end (non status pop up)
- Using the browser inspector and consulting the Network Response tab is the only way to find the message that describes why the upload failed
- version of Loris 19.0.0

**Comment by johnsaigle** [comment]
Note that this is an issue existing in other modules beyond just the `imaging_uploader`. Further work needs to be done to catalogue these occurrences.

In many cases the back-end will throw a `LorisException` or return a JSON-based error message. The front-end should process the errors and display them to the user.

Ideally the process of Reactifying will aid in this.

**Comment by driusan** [comment]
If you know of any other specific ones, please create a ticket for them so that we can keep track of which are unresolved.

**Comment by johnsaigle** [comment]
I'm going to close this because I can't really remember what I was talking about....

At the same time I think this has probably been addressed in the last few major releases as our Reactifcation process has progressed.

If there is an issue with modules not properly serving 500 errors we should open individual tickets for this.
