### ISSUE TITLE
package-lock.json: To commit or not to commit?

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#4408]
This file should either be committed explicitly to the repo or explicitly included in our `.gitignore`. Right now it floats around between branches and causes warnings when switching.

I'm not sure on the best practices here because I'm not really involved with JavaScript, but a decision should be made.

**Comment by johnsaigle** [comment]
I've assigned our resident JS specialists to sort this out. 👯

**Comment by maltheism** [comment]
@johnsaigle generally the best practice is to commit the package-lock.json. @HenriRabalais @zaliqarosli do you both agree or is there a reason we shouldn't in LORIS?

**Comment by maltheism** [comment]
Also see [stackoverflow answer](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5)

**Comment by johnsaigle** [comment]
Yeah I arrived at the same SO post but some people on that thread seem to have issues with it when doing merges etc. so :man_shrugging:

**Comment by zaliqarosli** [comment]
i don't have strong strong opinions but it seems like we should be committing it because 1. changes are only generated when node_modules or package.json are modified and 2. it must match package.json, so everytime package.json is committed, we should be committing package-lock.json alongside it. if the file exists on github, then we may as well be committing it. i think the issue right now is that the two files are out of sync with package-lock not getting updated when package was

<img width="780" alt="Screenshot 2019-03-20 13 12 30" src="https://user-images.githubusercontent.com/17415878/54704866-f8128000-4b11-11e9-9082-1452dbf13de2.png">

**Comment by zaliqarosli** [comment]
https://docs.npmjs.com/files/package-lock.json

**Comment by johnsaigle** [comment]
@zaliqarosli Yeah I think you're right that they're out of sync. Also `package-lock.json` appears to be only on `major`.

**Comment by maltheism** [comment]
Both @driusan and @xlecours are the only ones who have ever committed the file!
