### ISSUE TITLE
[statistics] Breakdown of Registered Candidates table always shows 0

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4546]
[TestPlan Demographic Statistics section
](https://github.com/aces/Loris/blob/minor/modules/statistics/test/TestPlan.md#demographic-statistics) 3 & 4

Problem:
Breakdown of Registered Candidates table always shows 0 no matter which option was selected.

**Comment by jftunteng** [comment]
@coreyAbout closing this issue since the PR is merged. Feel free to reopen if this is still an issue or if it reoccurs.

**Comment by kchatpar** [comment]
The statistics breakdown table in the demographics tab is still not being populated I'm getting the message on the front end:
Oops
It seems like the scan type selected does not have a corresponding column in the mri_parameter_form table in the database.
In order to display the statistics for the scan type, make sure the mri_parameter_form table contains a column in the exact format SCANTYPE_Scan_done

**Comment by ridz1208** [comment]
@kchatpar that is intended behaviour, the error message tells you that your mri_parameter_form instrument does not have the necessary data for your scan types

@kongtiaowang 's #4800 should allow you to load the table, or you could do it yourself by adding the missing columns and some data in them

**Comment by ridz1208** [comment]
@kchatpar I see that you reported this issue twice, im closing this one and copying my comment to the new one
