### ISSUE TITLE
[Instruments] All instruments (except bmi) break

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#4641]
on test.loris.ca, i am unable to access any instrument but the bmi

**Comment by kongtiaowang** [comment]
it is done.

**Comment by kongtiaowang** [comment]
The functions relating to getting the instrument's full name and getting the instrument's pages have been made abstract and must now be explicitly implemented to return the name string and pages array, rather than retrieving them from the database. The "LegacyInstrumentTrait" trait implements the old behaviour which can be restored by adding use LegacyInstrumentTrait; near the top of an instrument class. (This change is primarily motivated by an issue of cyclic dependencies while installing instruments, so there are no ill effects of using the trait on instruments which are already installed on a LORIS instance.)
