### ISSUE TITLE
[Dicom Archive] Data filter problems

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4708]
TestPlan Item 3 `Choose a parameter from the 'Selection Filter' that applies: [Automation Testing]`

Problems: 
choose site Montreal: ROM199_400199_V5 appears, which should belongs to Rome
choose site Ottawa: ROM240_400240_V6 and ROM221_400221_V5 appears, which should belong to Rome.
Data does not have "Series UID" column.

**Comment by cmadjar** [comment]
I just tested the site filter on the new imaging data and everything looks fine. It is highly probable that the problems were due to the crappy imaging dataset in raisin bread when testing the module.

Regarding the seriesUID, it is not shown in the data filter because there are multiple seriesUID per DICOM study. However, if you are looking for the archive with an image with a particular SeriesUID, then you can filter for that DICOM archive.
Example: SeriesUID 1.3.12.2.1107.5.2.32.35412.2010011213031389145301337.0.0.0 will only return one archive (2016/DCM_2016-08-15_ImagingUpload-18-25-i9GRv3.tar) because this acquisition was acquired during that DICOM study.

Closing this issue as the problems were related to the bad imaging data and all is good now.
