### ISSUE TITLE
[New Profile] Nothing happens upon creation of an invalid candidate

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#4867]
1. I set the pscid genration to 'user' in config.xml
2. I create a candidate and enter valid information in all the fields except the PSCID, which I set to '123456789'.
3. I click 'Create' and nothing happens...

**Comment by cmadjar** [comment]
The fix for this was merged yesterday on 21.0. I just pulled the latest code from 21.0 and it returns an error message now saying PSCID does not match the required structure.

![Screen Shot 2019-06-14 at 9 28 09 AM](https://user-images.githubusercontent.com/1402456/59512519-e6c5df00-8e86-11e9-8cb1-a39d590b8d00.png)

Closing this issue since it is now fixed.
