### ISSUE TITLE
[DQT] Remove null data from DQT for instruments not administered

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5053]
From redmine ticket https://redmine.cbrain.mcgill.ca/issues/6238. Not sure if still relevant.

When an instrument is not administered, an empty dataset still shows up when using the querying tool. We should update the DQT so only data for which an instrument with marked administration is included in the query.

**Comment by SantiagoTG** [comment]
Related issue: https://redmine.cbrain.mcgill.ca/issues/13144

Have all fields populate "No Admin" in DQT instead of blanks when the instrument has been marked "Complete - None"

Please have DQT generate "No Admin" for all fields once an instrument has been marked Data Entry = Complete, Administration = None

**Comment by driusan** [comment]
Not relevant to new DQT
