### ISSUE TITLE
Create a front end module for the history table.

### ISSUE THREAD

**Issue by samirdas** [aces/Loris#5090]
This is not urgent, but will come in handy for any clinical trials (Part 11 compliance)

**Comment by ridz1208** [comment]
@samirdas there might be a security concern with this one

@johnsaigle  ?

**Comment by johnsaigle** [comment]
It could maybe be done using a whitelist approach. If we only allow some known safe information - e.g. which user changed the state of some flag - then we could populate only that data.

It would be tricky though as the others mentioned because the info in the history table is meant to be accessed only by developers with full system access on a server where LORIS is installed. If this information is now available to front-end application admins then a lot of potentially sensitive data could be included in a much more vulnerable context.

**Comment by samirdas** [comment]
Good point. Let's discuss at the roadmap meeting, next week.

**Comment by christinerogers** [comment]
For the roadmap meeting -- what is stored in our History table doesn't satisfy compliance for clinical trials.   @samirdas i can remind you later.

**Comment by johnsaigle** [comment]
@driusan @ridz1208 Was there any progress on this during the roadmap meeting?

**Comment by ridz1208** [comment]
no, it was not brought up.

It's tricky that is on the back-burner for now

**Comment by driusan** [comment]
If this is required for compliance with individual modules they will keep their own history (ie. such as the issue tracker does), we have decided not to have a frontend of the history table itself for security reasons and because it is too big.
