### ISSUE TITLE
[Tools] A data-integrity checker

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5096]
Untill all tables in the database are normalized, all foreign keys are created and all cascades properly defined, it would be useful to have a tool that simply crawls through a given LORIS database and reports any and all data inconsistencies such as:

- duplicated examiners (due to typos in names, double spacing in name, ...)
- non-jsondata instruments with no SQL tables associated
- jsondata instruments WITH a SQL table created
- orphan flag entries (dont exists in the instrument tables)
- orphan instrument entries (dont exist in the flag table)

This ticket can be expanded to cover every possible case of inconsistent data that would be caught in a flawless database setup.

**Comment by johnsaigle** [comment]
Pasting @christinerogers comment from #5689 so that all of the desired DB checks can exist in one place

> quick notes:
~~(As john saigle mentioned ^^) #1053 is important~~ [_I do not remember saying this or know why it's relevant - JS_]
Date of birth should make sense, should not
check for duplicates - 1 participant with same instrument populated twice for 1 visit label (it happens)
DDE - over/under population
