### ISSUE TITLE
[Core] Improving File Download for large files

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5113]
Opening a placeholder issue for this Roadmap item. 
EEG, MRI download etc require a solution soon, beyond the reasonable size limits of http

This follows : 
* RM 15081 
* @johnsaigle 's responding PR #3881 ; requires discussion may be re-developed since John's #4181 is now merged.

**Comment by johnsaigle** [comment]
I'm planning to do a rewrite of #3881 now that #4181 is merged. Since the file downloader is like the "mirror image" of the uploader, I wanted to make sure that both were as similar as possible. Since the Uploader approach has been approved and is functional, I'll resume work on the Downloader shortly.

**Comment by johnsaigle** [comment]
I've added #6182 to serve as a generic way to handle file downloads.

I did some research yesterday and it seems that there is an Apache module that we could install that may help with large file downloads. It involves sending a special Response header `X-Sendfile` that should improve download performance for servers configured with the Apache module.

I'll look into this further and extend the class in the PR linked above if the Apache extension proves helpful.
