### ISSUE TITLE
[tools] Update project statistics script

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5120]
the project stats script `generate_project_statistics_csv.php`, created to get numbers from other projects  : 

- [ ] Print the $projectname in the csv output file : i.e. Move lines 23 and 24 down to 121, and prefix $projectname to $output_file
- [ ] Update email address to loris.info@mcin.ca (not exposed on the public listserv loris-dev@bic.mni.mcgill.ca )
- [ ] review for other updates since 2016...

from RM 8626

**Comment by johnsaigle** [comment]
Can you review #5989 and see whether it looks like what you want?

I did not add the project name to the CSV output file because it could cause issues with special characters. Raisinbread for instance has the project title "LORIS Demonstration Database" and the spaces will cause an issue in the filename.
