### ISSUE TITLE
[API] Examples in API Documentation

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#5161]
In the [API documentation](https://github.com/aces/Loris/blob/master/docs/API/LorisRESTAPI.md) there are no code examples given for pulling data from Loris. 

For example in section [1.1](https://github.com/aces/Loris/blob/master/docs/API/LorisRESTAPI.md#11-authentication) clients are supposed to write a POST request to get a token. For someone who only needs to pull data from, Loris it would be nice to have an example.

**Comment by johnsaigle** [comment]
The example you linked describes how to authenticate to LORIS. You can't pull data from LORIS without logging in via POST request first.

**Comment by johnsaigle** [comment]
@kchatpar I'm going to close this because the issue hasn't been very active for a while.

It looks to me like the API documentation has several examples using `GET` to pull various data from LORIS. 

POST is necessary to authenticate to LORIS even in the case of "open" datasets from my experience. 

If I've misunderstood or if you have further information about this, please feel free to re-open the issue.
