### ISSUE TITLE
Remove user-generated PSCID structure?

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5227]
There's a note in Utility about removing user-generated PSCIDs.

https://github.com/aces/Loris/blob/5aa861f791f6fb68c835c5a17b5e1564b0e40240/php/libraries/Utility.class.inc#L297-L311

Is this something that projects are using? If not, can we delete it?

**Comment by christinerogers** [comment]
I'd down-vote this.  It runs counter to many studies' actual workflow.  Subjects almost always have an internal ID informally assigned before they're registered in LORIS, because the order of registration in LORIS is not the same as the intake order (i.e. when recruiting/recording their name, phone, etc). 
This is because LORIS input often happens only when a scheduled visit/timepoint is imminent, or they fill out surveys/testing or sign consent.  
Ideally the intake ID can suggest the PSCID (Subject #7 -> PSCID MTL0007) to minimize risk of confusion for the study coordinator, and would not mandatorily be sequentially assigned.

**Comment by driusan** [comment]
@johnsaigle you're the one who added that note in 31dacf4e10

**Comment by johnsaigle** [comment]
@driusan That's how Git lays it out but if you dig a little that attribution goes to a PR containing a commit written by Justin Ng (and also @zaliqarosli). I think I just made the PR off of someone else's branch.

Do you have any idea why that note was referring to? Is this something we want to keep in LORIS?

**Comment by driusan** [comment]
I don't know what the note is referring to. @ridz1208 do you? You commented on the PR that @johnsaigle linked to above.

**Comment by driusan** [comment]
I sent a PR to just remove the note unless we come up with someone who knows what it's talking about.

**Comment by ridz1208** [comment]
@driusan I didnt comment on that part. I understand it as, this is necessary only for usergenerated PSCIDs. but it does make it sound like the goal is to remove that feature and I dont think we should.

Maybe we should move it to the PSCID class when It gets created ?

**Comment by driusan** [comment]
Why would the note be less confusing in the theoretical PSCID class?

**Comment by zaliqarosli** [comment]
@johnsaigle my name's only on there because I rebased for you. but looks like the line came from https://github.com/aces/Loris/pull/2889/files

**Comment by driusan** [comment]
So far we're still batting .000 for people who understand what the note is referring to..

**Comment by zaliqarosli** [comment]
lol if we have no plans to remove user-generated PSCID support, then we should probably just delete the note

**Comment by johnsaigle** [comment]
Closing this and #5229 removes the note.
