### ISSUE TITLE
Add variable in the config table to indicate if the instance of LORIs is DEV, STG or PROD

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#5267]
I think it would be useful to set-up a variable in the Config tables to track which environment we are dealing with.

Some tools/scripts are meant to be run only on PROD others are dangerous to run on PROD (deletions and other). we can in these scripts/tools check for the type on environment and abort the operation if its not the correct place

**Comment by ridz1208** [comment]
Got the idea from https://github.com/aces/Loris/pull/5260

**Comment by driusan** [comment]
I don't like this idea because the variable would get overwritten with the wrong value when taking a dump of production and putting it on staging/dev. It would be better to put it in config.xml, where it doesn't get overwritten... and on that note, what's wrong with the `<sandbox>` tag that already exists it config.xml?

**Comment by ridz1208** [comment]
You'r right, config.xml is a good place for it.

I'm not sure of the role of the existing sandbox flag. But I prefer having an explicit production/development flag. is there documentation anywhere about the role of the sandbox boolean ?

**Comment by driusan** [comment]
it's currently very lightly used.. I think it only affects a couple unit tests and whether " : DEV" shows up in header, but there's no reason it can't be used more.

**Comment by ridz1208** [comment]
I'm okai with that, closing ticket
