### ISSUE TITLE
[instrument builder] Regroup test plan to clarify what needs to be tested in the linst file

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#5484]
[test plan](https://github.com/aces/Loris/blob/22.0-release/modules/instrument_builder/test/TestPlan.md)
Item 1. a few step requires "Validate that not_answered option is added in the linst file for this question". This can only be done after save the linst file. Re-group this types of request together and put it after saved linst will improve the test process.

**Comment by cmadjar** [comment]
@christinerogers @coreyAbout can you guys work together in clarifying the test plan for that module please? Thanks!

**Comment by coreyAbout** [comment]
@cmadjar I will do a pull request and assign @christinerogers as a reviewer.

**Comment by christinerogers** [comment]
Hi Corey - thanks for this ticket. 
I'm not sure from old behaviour whether we expected not_answered to be visibly added in front end element in the Instrument Builder after the user clicks "Add Row".  
I will open a new "to verify" issue to ensure it doesn't get swept under the rug (though may be low-priority due to the incoming re-build of this module as discussed).
