### ISSUE TITLE
[RB] CandID 587630, sessionID 1053 : Visit stage should be In Progress

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#5684]
CandID  `587630`, sessionID `1053` : change `Visit stage` from `Pass` to `In Progress` - because many instruments are incomplete.  
RB SQL Dump should be edited.  This logical inconsistency should be checked on other candidates. 

Front-end view on Test vm (*edited* Nov.18 in the front-end to show `In Progress`): 
https://test-loris-dev.loris.ca/instrument_list/?candID=587630&sessionID=1053

_Why?_    So far this looks like the best demo candidate we have, and is being used accordingly for documentation screenshots by @knoll-alex.
Users are very likely to consult this candidate record in Demo. It should just make sense.

**Comment by johnsaigle** [comment]
I have a few questions here about what actionable tasks need to be done here.

I'm not sure what the screenshot is illustrating. Are you saying the November update now makes the candidate correct?

What makes that candidate the best demo candidate?

I'm not sure what sort of verification is done on the Raisinbread data. Maybe @ridz1208 can speak to its origins a little more. 

Do we have a tools script that can correct data problems (if any exist)?

**Comment by ridz1208** [comment]
@christinerogers I agree it should be corrected

@johnsaigle we don't currently have tools that do integrity checks like this one which explains why these were not done while cleaning RB. there is no way for a single person to go through all the possible scenarios of illogical data.  the only integrity check that was done during the cleanup of RB was, DOES RB LOAD ? that's pretty much it.

 - We should definitely fix these as we go. NOT DIRECTLY IN THE RB FILES but rather by loading the database changing what needs to be changed and redumping, otherwise we will end up with something like RB_data.sql which breaks everywhere.

 - We should have a database integrity checker script and consistently add checks to it when we detect these kind of issues. I guarantee you EVERY project has orphaned rows, illogical and inconsistent data. a while back justinNG had started a script that covered several base cases, it was never merged and eventually closed. I think it's very valuable to start that up again. It speaks to the health of the project.

**Comment by johnsaigle** [comment]
Agreed, this sounds very important.

Any chance you know the PR that he started?

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/pull/2764

**Comment by johnsaigle** [comment]
Do you know whether there is a ticket to resume this work? Should we create one?

The script seems pretty small; I think it would be nice to massage it a bit and then put it in the codebase. We can iteratively add more features as we need them.

**Comment by ridz1208** [comment]
no tickets that I know of. and yeah, iteratively adding checks would be awesome

**Comment by driusan** [comment]
The PR linked says there was ticket https://redmine.cbrain.mcgill.ca/issues/13717 created

**Comment by ridz1208** [comment]
oh yeah... redmine

**Comment by ridz1208** [comment]
Thank you stalebot

I think we should maybe start that up

**Comment by johnsaigle** [comment]
@ridz1208 #5689 is a ticket I created for this specifically just FYI
