### ISSUE TITLE
[login] Recaptcha not displaying

### ISSUE THREAD

**Issue by ridz1208** [aces/Loris#6244]
**Describe the bug**
The RECAPTCHA used to be available in a previous version when a user was requesting an account or even resetting a password.

I think the functionality should be restored

**Comment by johnsaigle** [comment]
This should be solved by #5214. @maltheism may be able to provide details about why reCAPTCHA hasn't been working for a while.

**Comment by maltheism** [comment]
Hey @ridz1208 I believe if my memory serves me correctly. The backend validation of answer from the frontend recaptcha isn't implemented last time I looked. I tested it awhile back with a recaptcha key and came to that conclusion. The login react PR will implement it for security because it keeps a lot of spam accounts being made.

**Comment by driusan** [comment]
Wasn't it removed after it was discovered that there was a bug for numerous releases where it wasn't being validated, proving it was useless?

**Comment by johnsaigle** [comment]
I don't remember it being removed. I think we just didn't fix it.

**Comment by maltheism** [comment]
Yes I remember that happened. I don't believe there could have ever been a LORIS successfully using RECAPTCHA when it wasn't validated or otherwise the RECAPTCHA process was completely useless because it was just continuing passed it.

**Comment by driusan** [comment]
@maltheism yes, that's my recollection.. and that's why it was removed.
