### ISSUE TITLE
[loris form] not answered date is not showing as empty but "dd/mm/yyyy"

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6268]
**Describe the bug**
A not answered date field is presented as "dd/mm/yyyy" instead of "empty", of course as a placeholder "dd/mm/yyyy" is ok, what if the user says the field is empty? This is not a big problem.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'instrument list'
2. Click on 'Radiology Review' or any similar instrument
3. See the date input box, if the field is not answered, is it a better practice to set the date field as empty instead of "dd/mm/yyyy", the latter is not an error, but not optimised.

**Server Environment (if known):**
- LORIS Version: 23.0

![image](https://user-images.githubusercontent.com/5295785/78566309-0733a100-77ed-11ea-882a-ec2df8753b04.png)

**Comment by driusan** [comment]
I believe the browser fills that in because the input field is an `<input type='date'>` element.. can you confirm? If so, I don't think there's anything we can do about this.

**Comment by maltheism** [comment]
Usually inputs allow a placeholder but like @driusan assumes that outcome of showing dd/mm/yyyy instead of empty is from the browser. I just tried placeholder set as empty string and I didn't have success. I think it can maybe be done with javascript but might be best to not mess with how the browser handles it.

**Comment by lingma** [comment]
Right, just leave it as is
