### ISSUE TITLE
[IssueTracker] ActiveIssues tab displays Status filter: Closed

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6517]
In the Issue Tracker `v23` : The `Active Issues` tab displays `Closed` in the Status filter element because the tab automatically filters for all issues *not Closed* (details below). 

The actual filtering _logic_ works well & as intended, and the data table filters appropriately for only active issues (*not* Closed). So this is a minor bug but still something users shouldn't be seeing. 

* Seems to be introduced during Reactification (#4112) 

Source: Active Issues tab `filterPresets` are defined: `{value: 'closed', opposite: true}}},` in [issueTrackerIndex.js Line 211](https://github.com/aces/Loris/blob/23.0-release/modules/issue_tracker/jsx/issueTrackerIndex.js#L211): 
```php
{label: 'Active Issues', filter: {status: {value: 'closed', opposite: true}}}, 
```

Can you advise on another way to select "all issues except Closed", @HenriRabalais ?

To reproduce: 
* Open the Issue Tracker
* Click `Active` tab. `Closed` appears printed in the Status filter, but the issues in the data table are clearly all except Closed issues (i.e. active)

Tested and reproduced on Firefox and Chrome, Loris 23 on test-loris-dev.loris.ca and sandbox

Originally reported in #6141

**Comment by HenriRabalais** [comment]
Yeah, so this was introduced when reactifying the module to deal with the fact that the issue track was filtering based on a "excludes" paradigmn, rather than the "includes" paradigm that (all?) other filters in loris are using. 

The  case described in this issue essentially was designed as place holder until a more robust system that allowed users to toggle between "includes", "excludes", "greater than", "lesser than", "equals", etc. was able to be implemented. 

A quick fix would be to conditionally display a ≠ symbol (or something to that effect) when the parameter "opposite" is set to true, so that it would be less confusing to the user. 

A future iteration should probably use a better system, and also allow the user to toggle between "includes" and "excludes".

**Comment by christinerogers** [comment]
Ok thanks @HenriRabalais. 
@laemtl is this something you'd like to tackle?

**Comment by laemtl** [comment]
Can we left the status field unpopulated as an alternative solution?

**Comment by laemtl** [comment]
Also, noticed that under the module filter, I have an entry [object Object]. I can open a separate issue.

**Comment by christinerogers** [comment]
> @christinerogers @HenriRabalais Can we left the status field unpopulated as an alternative solution?

Hi, yes the status value field can be unpopulated but the filter has to be applied on the data table -- otherwise there's no difference between the All Issues and Active Issues tabs. 
If there's a reasonably easy solution, let's handle this for the 23 release. 

If a new operator or React feature is needed to apply this filter, then this should probably be an issue/PR for `master` not the 23 release.  

> Also, noticed that under the module filter, I have an entry [object Object]. I can open a separate issue.
Can you elaborate, @laemtl ?  Is this related to the same bug?
