### ISSUE TITLE
[Issue Tracker] Filtered results and tab labels can disagree

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6533]
In the Issue Tracker v23, it is possible to select the Closed Issues tab, then play with the filters to select issues with other status. The results will be updated under the Closed Issues tab, where active issues can now be listed.

1. Go to Issue Tracker
2. Select a tab to filter the results (ex: Closed Issues)
3. Change the status filter for New  
5. All new issues are displayed under the Closed Issues tab

**Comment by laemtl** [comment]
@HenriRabalais, do you have any suggestion?

**Comment by HenriRabalais** [comment]
I guess this falls under a design decision. Currently, the way the tabs are working are as filter "presets" that will filter the data according to predetermined filter parameters. The user then has the option of altering those parameters as they see fit, independently of what tab they are on.

The solution to this issue could occur in a couple of ways that I can think of:
1. The defined presets are no longer tabs and are instead replaced by some sort of button/link/selection dropdown/etc. that can be clicked without being "active". These would trigger the preset filter, and then the user could change the filters afterward as they see fit.
2. When clicking on the tabs, the filter field that they alter becomes "deactivated". For example, if clicking on "Closed", the user would not be able to alter the Status Field on that tab because it will have disappeared.
3. We take away the tabs and filter presets since they are usually a single click away from the necessary filter.

I personally like option 1, because to me it is more inline with allowing users to create their own personal presets in the future which they can then quickly select. It's also similar to what websites like github have. 

<img width="991" alt="Screen Shot 2020-05-13 at 22 07 00" src="https://user-images.githubusercontent.com/7550451/81884526-24832a00-9566-11ea-8c0c-490cbe2c4462.png">

**Comment by laemtl** [comment]
I like option 1 too! Seems to ba an effective and easy way to avoid the confusion of the tabs.

**Comment by HenriRabalais** [comment]
I've created a PR that should resolve this issue as well as #6532. 

@laemtl @christinerogers Let me know you're thoughts on the design:
<img width="1423" alt="Screen Shot 2020-05-14 at 16 22 06" src="https://user-images.githubusercontent.com/7550451/81981980-1208ff00-95ff-11ea-912b-2b3259a4e80b.png">

**Comment by laemtl** [comment]
I will pull and test shortly. 
From the screenshot, I can already tell that this desgn is way clearer to me. I love it!

**Comment by christinerogers** [comment]
I'm fine with adding filter presets -- great idea -- given it makes sense to invest time implementing this across most modules.  I can think of IssueTracker, ConflictResolver, and maybe the Bvl and Img Feedback modules (someday) that would use this, off the top of my head...
It's sort of like saved queries - would also need mechanisms to edit/delete presets, and a button to "save current filter settings as a preset", and maybe a way to share/control presets across users.

**Comment by christinerogers** [comment]
@pierre-p-s this is the Issue Tracker bug you just raised -
It was found for 23 and this basically stalled on a re-design question :  
When the Module was updated for the DataFramework in 2019 the filter logic couldn't select for "_not Closed_" issues.
