### ISSUE TITLE
[docs] Update Unit Testing Guide for 23

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#6536]
If possible for the 23 release -- if not, for master: 
Update the Unit Test Guide for the current version of PHP, update the header of the doc, check that it works, etc... 
https://github.com/aces/Loris/blob/23.0-release/test/UnitTestGuide.md

**Comment by christinerogers** [comment]
Adding @laemtl 's suggestion for this issue: add an alias for this file from : https://github.com/aces/Loris/tree/23.0-release/docs/wiki/99%20-%20Developers

**Comment by johnsaigle** [comment]
What needs to be updated? If anything the header containing the date should be deleted. Git tracks the last time the file is modified and we won't be able to maintain it regularly.

> Adding @laemtl 's suggestion for this issue: add an alias for this file from : https://github.com/aces/Loris/tree/23.0-release/docs/wiki/99%20-%20Developers

This will break ReadTheDocs. See #6209.

**Comment by AlexandraLivadas** [comment]
I can make the minor changes to the header and I am currently testing that all the installation steps are still correct. Would there be any value in moving this to a different spot (like under `docs/wiki`) or should it be kept under the `test` directory? I can also make these changes in master instead of 23.0-release if that is the consensus.

**Comment by johnsaigle** [comment]
Yeah I think it would be good to move into the `docs/wiki/` section in the same place as the Automated Testing Guide.
