### ISSUE TITLE
[Documentation] ReadTheDocs issue with navigation tree

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6545]
On [ReadTheDocs](https://acesloris.readthedocs.io/en/latest)

Some section like this one:
[Docs » Study Parameters Setup » Study Variables » Introduction](https://acesloris.readthedocs.io/en/latest/wiki/01%20-%20STUDY%20PARAMETERS%20SETUP/01%20-%20Study%20Variables/00%20-%20Introduction%20to%20Study%20Variables/)

displays the breadcrumb sections out of order:
Docs » Study Variables » Study Parameters Setup » Introduction

cc @johnsaigle

**Comment by johnsaigle** [comment]
Possibly related to #6209 as this issue causes the ReadTheDocs build to fail.

**Comment by laemtl** [comment]
@johnsaigle Any help I can give on #6209?

**Comment by johnsaigle** [comment]
Yes, that would be great if you have some time!

You basically want to revert this PR which introduced the breaking changes:

https://github.com/aces/Loris/pull/6151/files

Specifically you'll move the API documentation somewhere under the the `docs/wiki/` directory. `mkdocs.yml` will need to be updated too.

Also, _ReadTheDocs is only built for `master` at the moment._ Any changes should be sent to `master`.

In order to properly test you may also need to create an account on ReadTheDocs and configure it to point to your fork of LORIS. If you run into issues with this let me know and I'll help with debugging.
