### ISSUE TITLE
[Configuration] 'Date display format' input not changing date display

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6554]
**Describe the bug**
Changing the settings for `Date display format` on the `Study` page of the configuration module does not change the date display format throughout the site.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to Configuration module
2. Change the date format in the `Date display format` at the bottom of the `Study` page
3. Save the option
4. Navigate throughout the site to find displayed dates
5. See error

**What did you expect to happen?**
Description of this option is `The Date format to use throughout LORIS for displaying date information`. I expected the format of the displayed dates such as `DoB` and `EDC` in the Access Profile page, etc to change when the format was modified.

**Comment by johnsaigle** [comment]
This was added in #5004. The original post may be helpful here:

>Following today's meeting, this adds a config option to allow projects to specify how they want dates to be displayed in LORIS.
**This PR only adds two quick examples of using this Config setting; it is by no means comprehensive.**
Also, this will only take place in "PHP contexts" and not within JS date elements as these are OS- and locale-dependent.

So this is happening not because of a bug but because this has not been implemented in all cases.

**Comment by CamilleBeau** [comment]
> not because of a bug but because this has not been implemented in all cases

Thank you @johnsaigle! I can close this issue in favour of your more specific one then?

**Comment by johnsaigle** [comment]
Sure that sounds good to me 👍 Thanks for opening this issue - hopefully we can get this fixed by the next release
