### ISSUE TITLE
[DQT] Unexpected results for age query 

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6588]
Filtering with Candidate Age <= 20 for All Visits 
output results with NULL age values and age above 20 (187.9, 33).
If there is a conversion from years (20) to days (7300), should this be clarified?

**To Reproduce**
Define Fields: oasi Data_entry & oasi Candidate_Age 
Define Filter: Candidate Age <= 20 for All Visits
Go to View Data
Run the Query

**Comment by ridz1208** [comment]
@laemtl 

The fact that it returns NULL values might be a bug.

The reason it outputs some ages > 20 is because for that same candidate other visits have age NULL which means it is returning that candidate because of that and subsequently reporting the age at the visit with a value higher than 20

I realise this is not super intuitive but if you switch from cross sectional to longitudinal view it makes a bit more sense.

As far as the NULL values being returned, the question would go to @LeighMac maybe ? should null values be returned when using > or < operators for compares?

**Comment by ridz1208** [comment]
@laemtl After a brief discussion with Leigh we have determined that this is currently the expected behaviour. we can revisit this issue more in depth when we get to the revamp of the DQT.

Thanks for reporting it
