### ISSUE TITLE
[imaging browser] data from projects the user is not affiliated is viewable

### ISSUE THREAD

**Issue by h-karim** [aces/Loris#6618]
**Describe the bug**
When viewing individual sessions, the user is able to alter the value of the`sessionID` GET variable  in the URL to view sessions from projects the user is not affiliated with. 
related to #6558 
**To Reproduce**
1. Grant the user "view all sites Imaging browser browser pages" permission
2. Navigate to the imaging browser front page
3. Click on one of the hyperlinks under the "Links" column
4. modify the `sessionID` number in the URL to a session belonging to a project the user is not affiliated with
5. Observe the url redirects successfully 

**Note**:  in step 1, you can alternatively  grant "view own site" permission and affiliate the user with all of the sites, or some of the sites, as long as the `sessionID` in step 4 is changed to a value for which the user is site-affiliated to.  
**What did you expect to happen?**
Since the user is not supposed to view sessions from projects that aren't user-affiliated, a permission message should appear not allowing the user to view the session.
**Browser Environment (please complete the following information):**
- OS: Ubuntu 18.04 LTS
- Browser: chrome 83.0.4103.61 and firefox 76.0.1

**Server Environment (if known):**
This was tested using the test VM for LORIS.

**Comment by christinerogers** [comment]
Same security concern as #6558

**Comment by christinerogers** [comment]
Should this be tagged critical for release, or addressed in later updates to the Data Framework implementation across modules?   @ridz1208 @driusan @johnsaigle   
* Same issue likely in #6558 for the Electrophys Browser

**Comment by johnsaigle** [comment]
I did a bit of digging and I don't think that this is a problem with the Data Framework per se. Its job is to limit the queries for tables, filtering based on Sites and Projects. It is accomplishing this.

The problem is that the individual sessions (in both modules) are not aware of Project permissions: they can be navigated to directly.

Permissions themselves aren't centrally managed. Instead, each module has a method `_hasAccess` which is responsible for determining which users can access data within the module. The bugs lie in these methods. If the contents of these methods are modified to check Project permissions, we should be good to go. 

Because this is not done centrally, it's possible that other modules will have these issues as well depending on their `_hasAccess()` methods.

https://github.com/aces/Loris/blob/a5304c762454fa8241ce0699af94b2da15f8879d/modules/imaging_browser/php/viewsession.class.inc#L49-L72

https://github.com/aces/Loris/blob/a5304c762454fa8241ce0699af94b2da15f8879d/modules/electrophysiology_browser/php/sessions.class.inc#L48-L55

**Comment by christinerogers** [comment]
Right -- in both of these modules the main page but not the subpage is appropriately checking project permissions.  
 I'll check for other modules whose subpages might be similarly under-updated.
