### ISSUE TITLE
[MRI Violations] No help text for this module's sub pages

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#7021]
**Describe the bug**
No help text was displayed when i clicked on the `?` on these sub pages:

- MRI Protocol Violations
- MRI Protocol Check Violations
- Resolved Violations

**Comment by haoweiqiu** [comment]
Hi @nicolasbrossard, I am not sure where I could find MRI Protocol Violations and MRI Protocol Check Violations. Could you help me with this? Thank you!

**Comment by christinerogers** [comment]
This issue is a duplicate of #5719 and #6575
It doesn't look like there was old help text that could be restored, we'll have to write this from scratch. 

Hi @haoweiqiu - mini-plan for this: 
Good resources to consult : 
* Page 24 of the Loris User Guide (slack me if you don't remember this doc) describes what these subpages do and where they are. 
* Click around on Demo to see how they work. 
* Look at the existing Help text for the MRI violations module (main page)
* Review the [Help Text Style Guide](https://github.com/aces/Loris/blob/main/docs/wiki/99_Developers/Help_Style_Guide.md) on how to write help text. 

Then, Commit a basic help text markdown for each, and I'll help you refine the text from there.
