### ISSUE TITLE
Data Query Tool: wrong field labels/descriptions displayed on the front end

### ISSUE THREAD

**Issue by GabrielPelletier** [aces/Loris#7511]
**Describe the bug**
When using the Data Query Tool on the front end, the back-end field names are correct, but the fields description/label displayed underneath are wrong.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run the lorisform_parser.php
2. Run the data_dictionnary_builder.php
3. Run CouchDB_Import_Demographics.php and CouchDB_Import_Instruments.php
4. Go on the DQT on the front end, pick any instrument or demographics
5. The same label is displayed for all the different fields (screenshot below)

**What did you expect to happen?**
The correct field description/label should be displayed under the right fields.

**Browser Environment (please complete the following information):**
- OS: Windows 10 (front end)
- Browser: Chrome

**Server Environment (if known):**
LORIS Version: v23.0.3

![image](https://user-images.githubusercontent.com/36201885/126691295-699aa956-f75a-4539-9b84-23823ae75f39.png)

**Comment by maltheism** [comment]
Hi @GabrielPelletier, this issue was fixed here: https://github.com/aces/Loris/pull/7098/files

You can modify your Loris instance modules/dataquery/jsx/react.fieldselector.js and add the following:
`desc = filteredItems[i].value.Description;`
**Note:** one line below 201 as seen in the commit history of the foregoing linked fix. Then you run the command `npm run compile` and visit your dataquery module to hopefully see the problem fixed.

**Comment by GabrielPelletier** [comment]
Great, this works.

**Comment by maltheism** [comment]
Awesome closing the issue then.
