### ISSUE TITLE
[create_timepoint] No error message to user if visit_label not set

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#7602]
**Describe the bug**
Step 4 of the TestPlan indicates: `Ensure that if the config.xml file does not contain a matching <visitLabel> entry, an error message should be displayed to the user.` 
For a subproject that does not have any visits set, no error message is displayed even though there are no visits available to select.

![image](https://user-images.githubusercontent.com/51176779/134977310-3313c871-882f-419a-a669-9418053103bf.png)

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to a candidate profile
2. Click on 'Create Timepoint'
3. Select a subproject that does not have any visitlabels set in the config.xml file
4. See that there is no error message

**What did you expect to happen?**
An error message to be displayed indicating that the subproject does not have any visits available.

**Comment by driusan** [comment]
@ridz1208 is this still an issue now that visit labels are out of the config.xml?

**Comment by ridz1208** [comment]
@driusan the issue is still happening but we now have deeper flaws in logic in that module.

1. The subproject dropdown is populated by looking at the candidate's registration project and the `project_subproject_rel` and only displaying subprojects associated with the registration project
2. the project dropdown is populated by looking at the USER's project affiliations and displaying ALL options regardless of selected subproject or `project_subproject_rel`
3. no error is displayed when the list of visits is empty but a prehistoric, **page breaking**, error is displayed when subprojects are empty
![image](https://user-images.githubusercontent.com/15268287/140096463-a917306c-da34-4de8-8ef4-4bd7bcf16712.png)

4. The code itself is a mess of duplications and wrong queries that needs to be cleaned up
![image](https://user-images.githubusercontent.com/15268287/140096897-ad8385b8-418a-4899-a625-6c11b473a290.png)

5. there is that requested feature of validating that the user is purposefully changing the project/site that will need this to be much more organized before it is added

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/issues/7730

**Comment by maltheism** [comment]
@ridz1208 am I to do the frontend part showing an error or the backend cleanup of code smell?
