### ISSUE TITLE
[Next Stage] Missing instrument in timepoint using Age Min/Max in battery

### ISSUE THREAD

**Issue by jstirling91** [aces/Loris#7641]
**Describe the bug**
When starting a new stage, instrument is missing when the candidate falls age at visit falls between Min and Max age. See [test plan](https://github.com/aces/Loris/blob/main/modules/next_stage/test/TestPlan.md) step 6

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
1. Create new test in Battery Manager setting the Min and Max age and subproject. Leave the visit label blank.
2. Create a new candidate
3. For new candidate, create a new timepoint, selecting the same subproject you used above.
4. Go to new timepoint and click Start Visit Stage.
5. Select a date which the candidates age will fall between the Min/Max age used above. Select yes to scan done
6. Click Start Visit and navigate to Visit page

**What did you expect to happen?**
The instrument used in step 1 above should show up in instrument list.

**Browser Environment (please complete the following information):**
- OS: Mac
- Browser Chrome

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 24.0.0
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by ridz1208** [comment]
@jstirling91 have you read https://github.com/aces/Loris/blob/main/modules/battery_manager/help/battery_manager.md ??

does it break the expected behaviour ?

**Comment by AlexandraLivadas** [comment]
@jstirling91 @ridz1208 As specified in [this](https://github.com/aces/Loris/blob/main/modules/battery_manager/help/battery_manager.md) file and also [step 7](https://github.com/aces/Loris/blob/main/modules/next_stage/test/TestPlan.md) of the test plan, if there is a battery entry with visit label set to NULL but there are other entries where the visit label is set, only the instruments with the visit label set to the current visit label should be displayed. I tested and this does not break that expected behaviour. 

For example, if there are no battery entries with a visit label set to V3 and there is a battery entry with a null visit label and AgeMin and AgeMax set and you create a session with visit label V3, that instrument (with the null visit label) will appear. But if I add a test battery entry with the visit label set to V3, the instrument with the null visit label will not appear. This is expected.

I think this issue can be closed if that sounds good for you.

**Comment by ridz1208** [comment]
@AlexandraLivadas thank you for checking!! I think @zaliqarosli expressed an interest to re-word the documentation to make it clearer. would you suggest we do that? as the documentation difficult to understand ?

**Comment by AlexandraLivadas** [comment]
@ridz1208 I think the help text makes the distinction clear but maybe the test plan could be updated to be a bit clearer. I'm on it!
