### ISSUE TITLE
[examiner][24.0 Testing] Error when creating an Examiner that already exists: swal should be updated

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7888]
**Describe the bug**
When creating a duplicate examiner, you get an error (yay!). But there's a new LORIS webpage that gets rendered in the swal.
Should either redirect to error page or display some other useful message in the swal. 

<img width="1539" alt="Screen Shot 2021-12-07 at 11 24 15 AM" src="https://user-images.githubusercontent.com/34260251/145067561-72c3d26e-a3a7-4896-bee1-8409cb8cefa7.png">

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Examiner' module
2. Create an examiner
3. Create a second examiner with same name and site info

**What did you expect to happen?**
A normal swal message

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 24 (main)

**Comment by jstirling91** [comment]
```
[Tue Dec 14 11:49:06.045444 2021] [php:notice] [pid 79006] [client 192.168.122.1:44324] Could not execute INSERT INTO examiners_psc_rel SET `examinerID`=:examinerID,`centerID`=:centerID. Stack trace#0 /var/www/Loris/php/libraries/Database.class.inc(265): Database->_realinsert()\n#1 /var/www/Loris/modules/examiner/php/examiner.class.inc(255): Database->insert()\n#2 /var/www/Loris/php/libraries/NDB_Menu_Filter_Form.class.inc(82): LORIS\\examiner\\Examiner->_process()\n#3 /var/www/Loris/php/libraries/LorisForm.class.inc(1453): NDB_Menu_Filter_Form->_save()\n#4 /var/www/Loris/php/libraries/NDB_Menu_Filter_Form.class.inc(50): LorisForm->process()\n#5 /var/www/Loris/php/libraries/NDB_Menu_Filter_Form.class.inc(110): NDB_Menu_Filter_Form->save()\n#6 /var/www/Loris/src/Middleware/UserPageDecorationMiddleware.php(241): NDB_Menu_Filter_Form->handle()\n#7 /var/www/Loris/src/Middleware/PageDecorationMiddleware.php(57): LORIS\\Middleware\\UserPageDecorationMiddleware->process()\n#8 /var/www/Loris/php/libraries/NDB_Page.class.inc(735): LORIS\\Middleware\\PageDecorationMiddleware->process()\n#9 /var/www/Loris/php/libraries/Module.class.inc(398): NDB_Page->process()\n#10 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): Module->handle()\n#11 /var/www/Loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()\n#12 /var/www/Loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()\n#13 /var/www/Loris/src/Middleware/ExceptionHandlingMiddleware.php(55): LORIS\\Router\\ModuleRouter->handle()\n#14 /var/www/Loris/src/Router/BaseRouter.php(126): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#15 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#16 /var/www/Loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#17 /var/www/Loris/htdocs/index.php(55): LORIS\\Middleware\\ContentLength->process()\n#18 {main}, referer: https://test-loris-dev.loris.ca/examiner/
```

**Comment by jstirling91** [comment]
@driusan @ridz1208 @cmadjar This issues seems to stem deeper than just the weird error pop out. There's a 500 error being thrown, see above comment, because the module is trying to insert the data. Furthermore, a similar issue is happening behind the scenes in 23.0 where the insert statement is failing. In 23.0 it seems like you got the correct error message but when you look at the error logs, you see the same error as above. It seems the the validation code of the module is properly identifying the error but is not catching it properly leading to the `_process` method to be triggered. This method should not be triggered in both 24.0 and 23.0 since it's partially saving data in the database. 

Try adding a duplicate examiner/site tuple where the examiner is not a radiologist. Set them as a radiologist in the add form and save it. You'll get an error but when you save the page the examiner is now set to a radiologist even thought the error was thrown.

**Comment by SantiagoTG** [comment]
In one case, I was able to create a duplicate examiner (Same name, same site), with the only difference that one instance 'Radiologist' is set to 'No', and in the other instance to 'Yes'. I was unable to replicate with other examiner accounts.

![Screen Shot 2022-02-25 at 2 30 17 PM](https://user-images.githubusercontent.com/54332302/155784968-61df593c-ddf7-4c1e-a4f6-4f596c490b35.png)

**Comment by CamilleBeau** [comment]
<img width="804" alt="image" src="https://github.com/user-attachments/assets/51c8cb26-6fe5-4f07-b53c-025c541cf627">
This is no longer an issue
