### ISSUE TITLE
Install ubuntu

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#8507]
## Comments
 - **insert comments here**

## Status
 - [x] Testing COMPLETE
 - [x] Partially Tested
 - [ ] Could Not Test (please specify reasons in comment)

Link to the document:
https://github.com/aces/Loris/tree/main/docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu

**Comment by miladheshmati** [comment]
Redmine ticket created requesting a blank VM for testing:

`https://redmine.cbrain.mcgill.ca/issues/20647`

**Comment by miladheshmati** [comment]
This section must have `sudo` in the beginning:

<img width="1302" alt="Screenshot 2023-04-11 at 3 43 24 PM" src="https://user-images.githubusercontent.com/51356424/231271697-0144228f-e8db-4cb0-a42f-6ea77159ab4f.png">

Otherwise, Permission denied error happens:

<img width="892" alt="Screenshot 2023-04-11 at 3 43 49 PM" src="https://user-images.githubusercontent.com/51356424/231271758-618f67cd-98d6-4482-9569-2158604f064a.png">

**Comment by miladheshmati** [comment]
<img width="937" alt="Screenshot 2023-04-11 at 3 53 49 PM" src="https://user-images.githubusercontent.com/51356424/231273896-b5bf00da-8825-4cb6-939d-0267b203c5dd.png">
