### ISSUE TITLE
[battery_manager] Numeric data table filters not working as expected

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/Loris#8565]
Numeric fields of the `FilterableDataTable` component do not work as expected.

Typing numbers in the `Minimum Age` and `Maximum Age` fields of the `Selection Filter` of the `battery_manager` module always returns an empty set for the `DataTable` when rows should be present for the criteria.

This has been tagged as belonging to this module because my search did not bring up other modules using numeric filters.

**Comment by zaliqarosli** [comment]
@jeffersoncasimir @driusan i had a look at this for shen. and the min/max age filters work as a strict match.
<img width="1431" alt="Screenshot 2023-04-12 at 3 08 25 PM" src="https://user-images.githubusercontent.com/17415878/231560084-183b0858-1a58-4121-85de-db504b0d2c3d.png">

i understand that a min/max filter should work at an in-between range, however we don't currently yet have this functionality in our jsx components. fixing this would be a new feature rather than a big fix. how do we want to proceed for this next release?

**Comment by driusan** [comment]
I think this is working as intended. Filters filter for an exact match, in this case it's just confusing because the column name is "minimum age" and "maximum age" so it sounds like it's a >= or <= criteria and not a = criteria despite the fact that filters do exact matches. I don't think there's much we can do about this.
