### ISSUE TITLE
[instrument_list] Wrong timepoint project - shows candidate registration project instead 

### ISSUE THREAD

**Issue by zaliqarosli** [aces/Loris#8784]
**Describe the bug**

https://github.com/aces/Loris/assets/17415878/e9444457-b629-4953-bb19-e3ba8a1c4ec2

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):

**What did you expect to happen?**

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

**Comment by driusan** [comment]
It looks like it comes from `$display.ProjectTitle` in smarty.

Display comes from:
``
    $this->tpl_data['display']
            = array_merge($this->candidate->getData(), $this->timePoint->getData());
```

Candidate::singleton adds a ProjectTitle, TimePoint does not. Should we update the header to be registration project?

**Comment by zaliqarosli** [comment]
thats a good solution but I feel like the Timepoint project should also be shown somewhere to avoid confusion. i think given timepoints not have projects, the timepoint class should probably have a get/set for project data

**Comment by driusan** [comment]
the TimePoint class does have getProject, but the template isn't calling getProject. The template is just merging the data arrays. The Candidate class includes `getProjectTitle()` method which directly stores the ProjectTitle (not the project) in the candidate's data array instead of using `getProject()->getName()` (like Timepoint does.) The TimePoint behaviour makes more sense, but ProjectTitle is stored directly in the Candidate data array, which is why just merging getData() from the two is picking up the one from Candidate. The template is looking for the variable ProjectTitle, not getting the project and then looking for the project's title.
