### ISSUE TITLE
[datadict] `data_dictionary_builder` bug

### ISSUE THREAD

**Issue by regisoc** [aces/Loris#9061]
**Describe the bug**

Running https://github.com/aces/Loris/blob/main/modules/datadict/test/TestPlan.md, last step fails on test v26 vm.

```
PHP Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`test_dev_260`.`publication_parameter_type_rel`, CONSTRAINT `FK_publication_parameter_type_rel_ParameterTypeID` FOREIGN KEY (`ParameterTypeID`) REFERENCES `parameter_type` (`ParameterTypeID`)) in /var/www/Loris/php/libraries/Database.class.inc:645
Stack trace:
#0 /var/www/Loris/php/libraries/Database.class.inc(645): PDO->exec()
#1 /var/www/Loris/tools/exporters/data_dictionary_builder.php(65): Database->run()
#2 {main}
 thrown in /var/www/Loris/php/libraries/Database.class.inc on line 645
```

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run the script. `tools/exporters/data_dictionary_builder.php`

**What did you expect to happen?**
should update the data dict

**Browser Environment (please complete the following information):**
- OS: 6.6.10-1-MANJARO
- Browser: Firefox 121.0.1 (64-bit)

**Server Environment (if known):**
v26 test vm

**Comment by ridz1208** [comment]
Unless I'm mistaken, this situation happens when a previous run of the script fails to complete. It creates a state when the script can not clean up old entries and regenerate the dictionary. Before reporting this as a bug with the script you should try to clear out the database manually (follow the logic of the script) and then run it again
